### ISSUE TITLE
Makefile not necessary

### ISSUE THREAD

**Issue by jmMeessen** [schottsfired/cjt-demo-environment#1]
It seems that the Makefile is not necessary. I propose to remove it so that the repo is leaner

**Comment by schottsfired** [comment]
I agree that it's not necessary, and I'm well aware. BUT it does show the general approach to start CJT with ``make cjt`` and will fail on the volume mapping (as expected). If one wants to continue using ``make``, they can. I didn't document it in the README ;)

**Comment by schottsfired** [comment]
Added a comment to the ``Makefile`` in 9e941bbb62cf490268d1a474da06b5238f2870bd
